sudo: true
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: pypy
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --yes fakeroot openssh-server
install:
  - pip install --requirement=requirements-travis.txt
  - LC_ALL=C CRYPTOGRAPHY_ALLOW_OPENSSL_102=true pip install .
script:
  - make check
  - make test
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
